# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export KUBECONFIG=/etc/kubernetes/admin.conf

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64
export M2_HOME=/tmp/apache-maven-3.8.1
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH
