pipeline {
     agent any

     tools {
	maven 'MAVEN381'
	jdk 'JAVA11'
     }
     stages {
          stage('Clone') {
              steps {
		git url: 'https://github.com/tektutor/devops-28june-02july-2021.git'
	      }
	  }
          stage('Compile') {
		steps {
			dir('Day5/JenkinsFilePipeline') {
				sh 'mvn clean compile'
			}
		}
	  }
          stage('Unit Test') {
		steps {
			dir('Day5/JenkinsFilePipeline') {
				sh 'mvn test'
			}
		}
	  }
          stage('Package') {
		steps {
			dir('Day5/JenkinsFilePipeline') {
				sh 'mvn package'
			}
		}
	  }
          stage('Install') {
		steps {
			dir('Day5/JenkinsFilePipeline') {
				sh 'mvn install'
			}
		}
	  }
	}
}
