- name: This play will install nginx, configure nginx to use custom document folder and will deploy a custom html page
  hosts: all 

  vars_files:
    - my_vars_file

  tasks:
    - include: "install-nginx-{{ansible_distribution|lower}}.yml"
    - include: common-nginx-tasks.yml
    - include: "configure-nginx-{{ansible_distribution|lower}}.yml"
